import EStyleSheet from "react-native-extended-stylesheet";

const styles = EStyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#fff",
    // justifyContent: "center",
    paddingTop: 32,
    paddingHorizontal: 32,
  },
  camera: {
    width: 343,
    height: 240,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    // border: 1 'solid' '#E8E8E8',
    // color: "#F6F6F6 ",
  },
  takePhotoButton: {
    width: 60,
    height: 60,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF",
  },
  addPhotoTitle: {
    color: "#BDBDBD",
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    fontStyle: "normal",
    fontWeight: 400,
    alignSelf: "flex-start",
    marginTop: 8,
    marginBottom: 32,
  },
  pictureInput: {
    width: 343,
    height: 43,
    // paddingTop: 16,
    // paddingBottom: 15,
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    fontStyle: "normal",
    fontWeight: 500,
    color: "#212121",
  },
  pictureInputContainer: {
    width: 343,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderBottomColor: "#E8E8E8",
    borderBottomWidth: 1,
    marginBottom: 16,
  },
  publishButton: {
    width: 343,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 32,
    paddingRight: 32,
    alignItems: "center",
    borderRadius: 100,
    backgroundColor: "#FF6C00",
    // marginBottom: 120,
  },
  BtnText: {
    // text-align: center;
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    fontStyle: "normal",
    fontWeight: 400,
    // line-height: normal,
    color: "#FFFFFF",
  },
  deleteButton: {
    width: 70,
    height: 40,
    backgroundColor: "#F6F6F6",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    bottom: 34,
  },
});

export default styles;
